USE MASTER
GO
DROP DATABASE QLBANHANG
GO
CREATE DATABASE QLBANHANG
GO
USE QLBANHANG
GO
CREATE TABLE KHACHHANG
(
	MAKH INT,
	HOTEN NVARCHAR(50),
	KHUYENMAI INT
	--CHO BIẾT SỐ VOUCHER KH TÍCH LŨY ĐƯỢC
)
CREATE TABLE SANPHAM
(
	MASP INT,
	TENSP NVARCHAR(30),
	SOLUONG INT,
	DONGIA INT
)
CREATE TABLE DONHANG
(
	MASP INT,
	MAKH INT,
	SOLUONG INT
)
CREATE TABLE TAIKHOAN
(
	MANGUODUNG INT,
	TENDANGNHAP VARCHAR(30),
	MATKHAU VARCHAR(10),
	LOAINGUODUNG INT,
	TINHTRANG INT
)
GO
INSERT KHACHHANG
VALUES(1, 'NGUYEN VAN A', 2),
	(2, 'NGUYEN VAN B', 0),
	(3, 'NGUYEN VAN C', 1),
	(4, 'NGUYEN VAN D', 2)
INSERT SANPHAM
VALUES(1, 'SACH CSDL', 2, 20000),
	(2, 'HANG TIEU DUNG', 10, 20000),
	(3, 'VAN PHONG PHAM', 15, 1000),
	(4, 'HOA MY PHAM', 20, 14000)
INSERT DONHANG
VALUES(1, 1, 2),
	(1, 2, 2),
	(3, 1, 2)
INSERT TAIKHOAN
VALUES(1, 'KH1', '123', 0, 1),
	(2, 'KH2', '123', 0, 1),
	(3, 'KH3', '123', 0, 0),
	(4, 'KH4', '123', 0, 1),
	(5, 'KH1', '123', 0, 1),
	(6, 'NV1', '123', 1, 1),
	(7, 'QT', '123', 2, 1)
--tạo login: tạo login để đăng nhập vào sql server
CREATE LOGIN LOGIN2 WITH PASSWORD='123'
CREATE LOGIN LOGIN3 WITH PASSWORD='123'
CREATE LOGIN LOGIN4 WITH PASSWORD='123'
CREATE LOGIN LOGIN5 WITH PASSWORD='123'
--tạo user: trong ứng dụng bán hàng có người dùng:
--khách hàng 1,2,3,4 //khách hàng được sửa thông tin cá nhân
CREATE USER KH2 FOR LOGIN LOGIN2
CREATE USER KH3 FOR LOGIN LOGIN3
--nhân viên:1,2 //nhân viên thêm sản phẩm, hóa đơn
CREATE USER NV1 FOR LOGIN LOGIN4
--quản trị:1 //quản trị quản lý tài khoản người dùng
CREATE USER QT1 FOR LOGIN LOGIN5
--phân quyền user
--TẠO CẤP QUYỀN
--CẤP QUYỀN THAO TÁC (THEM-XOA-SUA-XEM) TRÊN BẢNG SANPHAM CHO NHAN VIÊN
GRANT SELECT, INSERT, DELETE, UPDATE ON SANPHAM TO NV1
GRANT SELECT  ON SANPHAM(TENSP,SOLUONG,DONGIA) TO KH2,KH3
GO
--TẠO VIEW ĐỂ KH CHỈ ĐƯỢC TRUY CẬP TRÊN DỮ LIỆU CỦA MÌNH
CREATE 
--ALTER
VIEW UV_THONGKH
AS
	SELECT KHUYENMAI, HOTEN
	FROM KHACHHANG KH JOIN TAIKHOAN TK ON KH.MAKH = TK.MANGUODUNG
	WHERE TK.TENDANGNHAP = CURRENT_USER
GO
--CURRETUSER LÀ TÀI KHOẢN ĐANG ĐĂNG NHẬP 
--GÁN QUYỀN TRUY CẬP ĐẾN THÔNG TIN CÁ NHÂN
GRANT SELECT,UPDATE  ON UV_THONGKH TO KH2,KH3
--GÁN QUYỀN CHO ADMIN
GRANT ALL ON TAIKHOAN TO QT1
--TẠO ROLE 
CREATE ROLE KH
CREATE ROLE QT
CREATE ROLE NV
GO
--THÊM USER VÀO ROLE ĐỂ TIẾT KIỆM THỜI GIAN CẤP QUYỀN CHO SỐ LƯỢNG LỚN USER
EXEC SP_ADDROLEMEMBER 'KH' ,'KH2'
EXEC SP_ADDROLEMEMBER 'QT' ,'QT1'
EXEC SP_ADDROLEMEMBER 'NV' ,'NV1'
--CẤP QUYỀN CHO ROLE
GRANT UPDATE ON DONHANG (SOLUONG) TO KH
--TEST THỬ BẰNG CÁCH LOGIN VÀO TÀI KHOẢN VD NHƯ LOGIN2 ~ USER2 ĐỀ XEM USER CÓ ĐƯỢC QUYỀN TRÊN BẢNG KO
SELECT HOTEN
FROM KHACHHANG
